### ISSUE TITLE
Update Device Widget

### ISSUE THREAD

**Issue by MahmoudAyman** [Sudotechs/data-logger-UI#28]
### Description
The widgets [cards] used to display Gateways and Nodes require some enhancement to show user-readable information, making the design more intuitive and distinguishing between Gateways and Nodes.

### Extended Considerations

- The Title of the Device [either nodes or gateways] should be Bold and in bigger font. Choose any type of visual designator to differentiate between gateways and nodes [maybe render the widget in a different color based on the device type, add a different icon, or change the color of the widget's header.....etc]
- change the appearance of the widget to appear smaller and more asestatically appealing [maybe use elements from the design system @Nahla-Kh created]
- Add a "show info" button, maybe a simple down-arrow at the bottom right corner of the widget. When pressed it enlarges the widget and shows the meta-data from the device object as following:
-       Type (string) [e.g. PV500] 
-       LifeBox ID (number)
-       Installation Date (date-time)
**[NOTE]** meda-data of the "thing" object currently does not contain these information, @ahmedelgamal0 will be updating it soon, for now implement the logic and add condition if these info are not available (i.e. null) show "Not Configured" instead.
- Add a small warning label [the yellow triangle] that appears if that device has active warninings/notifications. You can make it invisible, and only enable it if the thing object retrieved has active alarms (within meta-data) [again make it invisible in case meta-data does not contain member "active-alarms" i.e. not implemented.

### Implementation Details

- Use the existing components if available, if not refer to the design system by @Nahla-Kh
- publish your code to the branch linked to this issue
- Document your code

### Task List

- [x]  Improve Node/Gateway widget design
- [x]  Add alarm icon
- [x]  Add support for meta-data
- [x]  Distinguish between node and gateway widgets.
- [x]  Update widget card to replace last-updated with last-connected.

**Comment by MohamedKhaleel1414** [comment]
The solution for this issue is published in a new branch called "fix-issue-28".
You can find the documentation of my work related to this issue in a folder called "documentation" in the root directory. The file is called by the number of the issue.

**Comment by MahmoudAyman** [comment]
Great work. I have edited the issue to include one more modification, replace the last-updated element in the device widget with last-connected. This will also be a member of the device object [not inside meta data] if not implemented display not configured.

**Comment by MahmoudAyman** [comment]
I'm not sure what you mean by that, can you explain it further? This won't affect this issue tho.
